# Generated by Django 5.2 on 2026-07-06 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_product_occasion'),
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='chosen_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_picks', to='products.product'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='skip_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('acted_on', 'Acted on'), ('snoozed', 'Snoozed'), ('skipped', 'Skipped')], default='sent', max_length=20),
        ),
    ]
