# Generated by Django 5.2 on 2026-07-07 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_add_product_occasion'),
        ('reminders', '0003_occasion_snoozed_until_reminderlog_chosen_product_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGiftProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('ordered', 'Ordered')], default='pending_approval', max_length=20)),
                ('delivery_date', models.DateField()),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_gift_proposals', to='reminders.occasion')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_gift_proposals', to='orders.order')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_gift_proposals', to='subscriptions.usersubscription')),
                ('suggested_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_gift_proposals', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_gift_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
