# Generated by Django 5.2 on 2026-07-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_growth_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_anonymous_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='occasion_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
