# Generated by Django 5.2 on 2026-07-06 22:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('model_type', models.CharField(choices=[('spoil_box', 'Monthly Spoil Box'), ('someone_to_spoil', 'Someone to Spoil'), ('gift_credit', 'Gift Credit'), ('occasion_auto', 'Occasion Auto-Gift')], max_length=30)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
