# Generated by Django 5.2 on 2026-07-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_billing_and_auto_gift'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_gift_subscriptions', to='reminders.occasion'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
