# Generated by Django 5.2 on 2026-07-07 00:54

import apps.group_gifts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_growth_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(default=apps.group_gifts.models.generate_share_token, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('cart_snapshot', models.JSONField(default=list)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_type', models.CharField(default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_gifts', to='orders.order')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupGiftContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=150)),
                ('contributor_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='group_gifts.groupgift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
