# Generated by Django 5.2 on 2026-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('thank_you', 'Thank You'), ('just_because', 'Just Because'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
