# Generated by Django 5.2 on 2026-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_product_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_mode',
            field=models.CharField(choices=[('image', 'Image overlay'), ('model_3d', '3D model')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_scale',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
